[build]
  publish = "_site"
  command = "bundle install && JEKYLL_ENV=production bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.2.2"
  JEKYLL_ENV = "production"

# Cache bundler
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200
