hero_image: /img/header-bg.jpg
events_hero_image: /img/portfolio/bg-events.jpg
services_hero_image: /img/services/bg-services.jpg
testimonials_hero_image: /img/team/bg-testimonials.jpg
about_hero_image: /img/about/bg-about.jpg
contact_hero_image: /img/map-image.png
site_tagline: "Tarot & Yoga to align mind, body, and purpose."
